pipeline:
  build:
    image: mhart/alpine-node-auto:latest
    commands:
      - npm i
      - npm run build

  test:
    image: mhart/alpine-node-auto:latest
    commands:
      - npm i
      - npm run build
      - npm test

  docker:
    image: plugins/docker
    registry: registry.gitlab.com
    repo: registry.gitlab.com/simontegg/enterprise-stack
    secrets: [docker_username, docker_password]

  rancher:
    image: peloton/drone-rancher
    url: http://104.237.4.81:8080
    access_key: ${PLUGIN_ACCESS_KEY}
    secret_key: ${PLUGIN_SECRET_KEY}
    service: Accreditron/web
    docker_image: registry.gitlab.com/simontegg/enterprise-stack
