pipeline:
  build:
    image: dmitry7887/alpine-node-git
    secrets: [docker_username, docker_password]
    commands:
      - npm install
      - npm run build

  test:
    image: dmitry7887/alpine-node-git
    secrets: [docker_username, docker_password]
    commands:
      - npm install
      - npm run build
      - npm test

  docker:
    image: plugins/docker
    registry: registry.gitlab.com
    repo: registry.gitlab.com/simontegg/enterprise-stack
    secrets: [docker_username, docker_password]

  rancher:
    image: peloton/drone-rancher
    url: http://104.237.4.81:8080
    secrets: [PLUGIN_ACCESS_KEY, PLUGIN_SECRET_KEY]
    service: Accreditron/staging
    docker_image: registry.gitlab.com/simontegg/enterprise-stack
