pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  build:
    image: dmitry7887/alpine-node-git
    commands:
      - npm install
      - npm run build
    cache:
      mount: 
        - node_modules
        - .git

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  test:
    image: dmitry7887/alpine-node-git
    commands:
      - npm test

  docker:
    image: plugins/docker
    registry: registry.gitlab.com
    repo: registry.gitlab.com/simontegg/enterprise-stack
    secrets: [docker_username, docker_password]

  rancher:
    image: peloton/drone-rancher
    url: http://104.237.4.81:8080
    secrets: [PLUGIN_ACCESS_KEY, PLUGIN_SECRET_KEY]
    service: Accreditron/staging
    docker_image: registry.gitlab.com/simontegg/enterprise-stack
    timeout: 60
    confirm: true
