pipeline:
  build:
    image: dmitry7887/alpine-node-git
    commands:
      - npm install
      - npm run build
    cache:
      mount: 
        - node_modules
        - .git

  test:
    image: dmitry7887/alpine-node-git
    commands:
      - npm install
      - npm run build
      - npm test

  rancher:
    image: peloton/drone-rancher
    url: http://104.237.4.81:8080
    secrets: [PLUGIN_ACCESS_KEY, PLUGIN_SECRET_KEY]
    service: Accreditron/staging
    docker_image: registry.gitlab.com/simontegg/enterprise-stack
    confirm: true
