pipeline:
  build:
    image: mhart/alpine-node-auto:latest
    commands:
      - npm i
      - npm run build

  test:
    image: mhart/alpine-node-auto:latest
    commands:
      - npm i
      - npm run build
      - npm test

  publish:
    image: plugins/docker
    repo: registry.gitlab.com/simontegg/enterprise-stack
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
