# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  POSTGRES_DB: test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DATABASE_URL: postgresql://postgres:postgres@postgres/test

#cache:
#  paths:
#    - node_modules/
before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages: 
  - build
  - test

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

test_unit:
  stage: test
  script:
    - docker run $IMAGE_TAG npm test

test_integration:
  stage: test
  script:
    - docker run -d -e "POSTGRES_USER=postgres" -e "POSTGRES_PASSWORD=postgres" -e "POSTGRES_DB=test" postgres:9.5
    - docker run -e --link=postgres:db "DATABASE_URL=postgresql://postgres:postgres@postgres/test" $IMAGE_TAG npm run test:integration


