version: '2'
services:
  postgres:
    restart: always
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    volumes:
      #      - /var/run/docker.sock:/var/run/docker.sock
       - ./data/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgresql://postgres:postgres@postgres/test
  integration-tests:
    image: app
    command: ['./bin/wait-for-postgres.sh', 'postgres', 'npm run test:integration']
  #  command: npm run test:integration
    depends_on:
      - postgres
      - app
