version: '2'
services:
  postgres:
    restart: always
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER:'postgres'
      - POSTGRES_PASSWORD:'postgres'
      - POSTGRES_DB:'test'
    ports:
      - '5432:5432'
  app:
    build: .
    volumes:
      - "./api/src:/app/src"
    ports:
      - "3000:3000"
    links:
      - postgres
